dataset_url: "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
dataset_path: "creditcard.csv"
model_path: "autoencoder_model.pkl"
scaler_path: "scaler.pkl"
metrics_path: "metrics.json"
roc_path: "roc.png"
pr_path: "pr.png"
cm_path: "cm.png"
hist_path: "hist.png"

target: "Class"
drop: ["Time"]

test_size: 0.2
random_state: 42

contamination: 0.001
epochs: 30
batch_size: 128
hidden_neurons: [64, 32, 64]
